### PR TITLE
Add more flexibility, add build up icons enum

### PR DESCRIPTION
**Pull request by RusinovAnton**
Hey, I've customized you code for my own purposes and thought that it might be interesting for you.

### CODE REVIEW

**Comment by Gaya** [comment]
Thanks for this. How are you using this enum in your code? Just so I can paint a better understanding and write something in the docs to clarify.

**Comment by RusinovAnton** [comment]
@Gaya, ok. so lets say I want to include whole icon set from the `icons/react-icons` folder
// style.scss
```scss
// I'm going to change icons folder path
$sprite-icons-folder: 'icons/react-icons/*.png';
$sprite-icons-2x-folder: 'icons/react-icons/*.png';
// and set custom icon prefix
$sprite-icons-class-prefix: 'react-icon_';

@import 'sprite/retina-sprites';
// so I need just import _sprite-icons-enum.scss file after _retina-sprites.scss
// and it will generate stylesheet with whole set of icons.
@import 'sprite/sprite-icons-enum';
```

Now when I add .png icons to the destination folder and run styles build it will generate corresponding styles automatically.

**Comment by Gaya** [comment]
Thanks! I will merge this into the library. Great work!

**Comment by RusinovAnton** [comment]
@Gaya, are you going to bump bower package version? Also are you going to publish package on npm?

**Comment by Gaya** [comment]
Right. I'll do that later today. Thanks for the heads up

**Comment by Gaya** [comment]
Changes have been version bumped and module is also available on npm now

**Pull request merged**
